import React from "react";
import { WidgetDefinition, DashboardLayout } from "./types";
import { WinRateSummaryWidget } from "./widgets/WinRateSummaryWidget";
import { TodayWidget } from "./widgets/TodayWidget";
import { CurrentStreakWidget } from "./widgets/CurrentStreakWidget";
import { WinRateTrendWidget } from "./widgets/WinRateTrendWidget";
import { RecentMatchesWidget } from "./widgets/RecentMatchesWidget";
import { FormatDistributionWidget } from "./widgets/FormatDistributionWidget";
import { DeckSpotlightWidget } from "./widgets/DeckSpotlightWidget";
import { RecentAchievementsWidget } from "./widgets/RecentAchievementsWidget";
import { FeaturedLeaderboardWidget } from "./widgets/FeaturedLeaderboardWidget";
import { FunFactsWidget } from "./widgets/FunFactsWidget";
import { FrequentOpponentsWidget } from "./widgets/FrequentOpponentsWidget";
import { PlayVsDrawWidget } from "./widgets/PlayVsDrawWidget";
import { VictoryBreakdownWidget } from "./widgets/VictoryBreakdownWidget";
import { LifeClosenessWidget } from "./widgets/LifeClosenessWidget";
import { ActivityHeatmapWidget } from "./widgets/ActivityHeatmapWidget";
import { LuckyCursedCardsWidget } from "./widgets/LuckyCursedCardsWidget";
import { GuildMasteryWidget } from "./widgets/GuildMasteryWidget";
import { MulliganMeterWidget } from "./widgets/MulliganMeterWidget";
import { ArchetypeClashWidget } from "./widgets/ArchetypeClashWidget";
import {
  Trophy,
  Calendar,
  Flame,
  TrendingUp,
  Swords,
  Layers,
  Sparkles,
  Award,
  Crown,
  Lightbulb,
  Users,
  ArrowLeftRight,
  HeartPulse,
  Flag,
  BarChart3,
  Shield,
  PieChart,
  Gauge,
  Target,
} from "lucide-react";

export const WIDGET_REGISTRY: Record<string, WidgetDefinition> = {
  win_rate_summary: {
    kind: "win_rate_summary",
    title: "All-Time Win Rate",
    subtitle: "Lifetime record",
    icon: <Trophy className="w-3.5 h-3.5" />,
    defaultWidth: 4,
    defaultHeight: 1,
    defaultSettings: {},
    component: WinRateSummaryWidget,
  },
  today: {
    kind: "today",
    title: "Today Win Rate",
    subtitle: "Current session",
    icon: <Calendar className="w-3.5 h-3.5" />,
    defaultWidth: 4,
    defaultHeight: 1,
    defaultSettings: {},
    component: TodayWidget,
  },
  current_streak: {
    kind: "current_streak",
    title: "Current Streak",
    subtitle: "Active streak",
    icon: <Flame className="w-3.5 h-3.5" />,
    defaultWidth: 4,
    defaultHeight: 1,
    defaultSettings: {},
    component: CurrentStreakWidget,
  },
  win_rate_trend: {
    kind: "win_rate_trend",
    title: "Trending Win Rate",
    subtitle: "Rolling performance",
    icon: <TrendingUp className="w-3.5 h-3.5" />,
    defaultWidth: 7,
    defaultHeight: 3,
    defaultSettings: {
      timeRange: "14D",
      formatFilter: "ALL",
    },
    component: WinRateTrendWidget,
  },
  deck_spotlight: {
    kind: "deck_spotlight",
    title: "Deck Spotlight",
    subtitle: "Featured deck",
    icon: <Sparkles className="w-3.5 h-3.5" />,
    defaultWidth: 5,
    defaultHeight: 3,
    defaultSettings: {},
    component: DeckSpotlightWidget,
  },
  recent_matches: {
    kind: "recent_matches",
    title: "Recent Matches",
    subtitle: "Latest activity",
    icon: <Swords className="w-3.5 h-3.5" />,
    defaultWidth: 5,
    defaultHeight: 3,
    defaultSettings: {
      limit: 10,
    },
    component: RecentMatchesWidget,
  },
  format_distribution: {
    kind: "format_distribution",
    title: "Format Distribution",
    icon: <PieChart className="w-3.5 h-3.5" />,
    defaultWidth: 4,
    defaultHeight: 2,
    defaultSettings: {},
    component: FormatDistributionWidget,
  },
  fun_facts: {
    kind: "fun_facts",
    title: "Fun Facts",
    subtitle: "Play telemetry",
    icon: <Lightbulb className="w-3.5 h-3.5" />,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultSettings: {},
    component: FunFactsWidget,
  },
  recent_achievements: {
    kind: "recent_achievements",
    title: "Recent Achievements",
    subtitle: "Latest trophies",
    icon: <Award className="w-3.5 h-3.5" />,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultSettings: {
      limit: 4,
    },
    component: RecentAchievementsWidget,
  },
  featured_leaderboard: {
    kind: "featured_leaderboard",
    title: "Featured Leaderboard",
    subtitle: "Hall of fame records",
    icon: <Crown className="w-3.5 h-3.5" />,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultSettings: {
      category: "combat_single_hit",
    },
    component: FeaturedLeaderboardWidget,
  },
  frequent_opponents: {
    kind: "frequent_opponents",
    title: "Frequent Opponents",
    subtitle: "Most faced rivals",
    icon: <Users className="w-3.5 h-3.5" />,
    defaultWidth: 5,
    defaultHeight: 3,
    defaultSettings: {
      limit: 6,
    },
    component: FrequentOpponentsWidget,
  },
  play_vs_draw: {
    kind: "play_vs_draw",
    title: "Play vs. Draw",
    subtitle: "First-turn advantage",
    icon: <ArrowLeftRight className="w-3.5 h-3.5" />,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultSettings: {},
    component: PlayVsDrawWidget,
  },
  victory_breakdown: {
    kind: "victory_breakdown",
    title: "Victory Breakdown",
    subtitle: "Win condition analysis",
    icon: <Flag className="w-3.5 h-3.5" />,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultSettings: {},
    component: VictoryBreakdownWidget,
  },
  life_closeness: {
    kind: "life_closeness",
    title: "End-Game Life Totals",
    subtitle: "Victory health margins",
    icon: <HeartPulse className="w-3.5 h-3.5" />,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultSettings: {},
    component: LifeClosenessWidget,
  },
  activity_heatmap: {
    kind: "activity_heatmap",
    title: "Activity by Day",
    subtitle: "Volume & win rate trends",
    icon: <BarChart3 className="w-3.5 h-3.5" />,
    defaultWidth: 12,
    defaultHeight: 3,
    defaultSettings: {},
    component: ActivityHeatmapWidget,
  },
  lucky_cursed_cards: {
    kind: "lucky_cursed_cards",
    title: "Lucky Charms & Cursed Spells",
    subtitle: "Card win rate impact",
    icon: <Sparkles className="w-3.5 h-3.5" />,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultSettings: {},
    component: LuckyCursedCardsWidget,
  },
  guild_mastery: {
    kind: "guild_mastery",
    title: "Guild & Clan Mastery",
    subtitle: "Best & worst color pairs",
    icon: <Shield className="w-3.5 h-3.5" />,
    defaultWidth: 12,
    defaultHeight: 3,
    defaultSettings: {},
    component: GuildMasteryWidget,
  },
  mulligan_meter: {
    kind: "mulligan_meter",
    title: "Mulligan Resilience Meter",
    subtitle: "Opening hand win drop-off",
    icon: <Gauge className="w-3.5 h-3.5" />,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultSettings: {},
    component: MulliganMeterWidget,
  },
  archetype_clash: {
    kind: "archetype_clash",
    title: "Archetype Pace Matrix",
    subtitle: "Aggro / Midrange / Control",
    icon: <Target className="w-3.5 h-3.5" />,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultSettings: {},
    component: ArchetypeClashWidget,
  },
};

const WIDGET_ALIASES: Record<string, string> = {
  format_breakdown: "format_distribution",
  radial_format_dial: "format_distribution",
};

export function getWidgetDefinition(kind: string): WidgetDefinition | undefined {
  const resolvedKind = WIDGET_ALIASES[kind] || kind;
  return WIDGET_REGISTRY[resolvedKind];
}

export const DEFAULT_DASHBOARD_LAYOUT: DashboardLayout = {
  schema_version: 1,
  widgets: [
    {
      id: "widget-win-rate-summary",
      kind: "win_rate_summary",
      x: 0,
      y: 0,
      width: 4,
      height: 1,
      settings: {},
    },
    {
      id: "widget-today",
      kind: "today",
      x: 4,
      y: 0,
      width: 4,
      height: 1,
      settings: {},
    },
    {
      id: "widget-current-streak",
      kind: "current_streak",
      x: 8,
      y: 0,
      width: 4,
      height: 1,
      settings: {},
    },
    {
      id: "widget-win-rate-trend",
      kind: "win_rate_trend",
      x: 0,
      y: 1,
      width: 7,
      height: 3,
      settings: {
        timeRange: "14D",
        formatFilter: "ALL",
      },
    },
    {
      id: "widget-deck-spotlight",
      kind: "deck_spotlight",
      x: 7,
      y: 1,
      width: 5,
      height: 3,
      settings: {},
    },
    {
      id: "widget-recent-matches",
      kind: "recent_matches",
      x: 0,
      y: 4,
      width: 5,
      height: 3,
      settings: {
        limit: 10,
      },
    },
    {
      id: "widget-format-distribution",
      kind: "format_distribution",
      x: 5,
      y: 4,
      width: 3,
      height: 3,
      settings: {},
    },
    {
      id: "widget-fun-facts",
      kind: "fun_facts",
      x: 8,
      y: 4,
      width: 4,
      height: 3,
      settings: {},
    },
    {
      id: "widget-recent-achievements",
      kind: "recent_achievements",
      x: 0,
      y: 7,
      width: 6,
      height: 3,
      settings: {
        limit: 4,
      },
    },
    {
      id: "widget-featured-leaderboard",
      kind: "featured_leaderboard",
      x: 6,
      y: 7,
      width: 6,
      height: 3,
      settings: {
        category: "combat_single_hit",
      },
    },
    {
      id: "widget-frequent-opponents",
      kind: "frequent_opponents",
      x: 0,
      y: 10,
      width: 6,
      height: 3,
      settings: {
        limit: 6,
      },
    },
    {
      id: "widget-play-vs-draw",
      kind: "play_vs_draw",
      x: 6,
      y: 10,
      width: 6,
      height: 3,
      settings: {},
    },
    {
      id: "widget-victory-breakdown",
      kind: "victory_breakdown",
      x: 0,
      y: 13,
      width: 6,
      height: 3,
      settings: {},
    },
    {
      id: "widget-life-closeness",
      kind: "life_closeness",
      x: 6,
      y: 13,
      width: 6,
      height: 3,
      settings: {},
    },
    {
      id: "widget-lucky-cursed-cards",
      kind: "lucky_cursed_cards",
      x: 0,
      y: 16,
      width: 6,
      height: 3,
      settings: {},
    },
    {
      id: "widget-mulligan-meter",
      kind: "mulligan_meter",
      x: 6,
      y: 16,
      width: 6,
      height: 3,
      settings: {},
    },
    {
      id: "widget-archetype-clash",
      kind: "archetype_clash",
      x: 0,
      y: 19,
      width: 6,
      height: 3,
      settings: {},
    },
    {
      id: "widget-activity-heatmap",
      kind: "activity_heatmap",
      x: 6,
      y: 19,
      width: 6,
      height: 3,
      settings: {},
    },
    {
      id: "widget-guild-mastery",
      kind: "guild_mastery",
      x: 0,
      y: 22,
      width: 12,
      height: 3,
      settings: {},
    },
  ],
};
